name: ec2에 배포 실행

on:
  push:
    tags:
      - 'deploy*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Save SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: SSH into EC2 and run run.sh
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/projects/prj3
            git fetch --all --tags
            git checkout ${{ github.ref_name }}
            chmod +x run.sh
            ./run.sh
          EOF
